const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const values=new Map();
const localStorage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,String(v)),removeItem:k=>values.delete(k)};
const ctx={window:{},localStorage,console,Date,Set,Map,JSON,URLSearchParams};ctx.window=ctx;vm.createContext(ctx);
const load=f=>vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
load('mashup-core.js');load('engine/contracts/data/item-identity.js');
assert.strictEqual(ctx.BillyItemIdentity.key(ctx.BillyItemIdentity.mashup('🐷','🥓')),`mashup:${ctx.BillyMashups.id('🐷','🥓')}`);
assert.deepStrictEqual({...ctx.BillyItemIdentity.parseKey('base-emoji:😀')},{type:'base-emoji',id:'😀'});
load('engine/platform/storage/storage.js');load('engine/game/publishing/curator-records.js');load('games/billyslab/content/curator-repository.js');
const saved=ctx.BillyCuratorData.save('😀|😎',{left:'😀',right:'😎',blurblet:' Test ',notes:'private'});
assert.strictEqual(saved.recordType,'curator-draft');
const published=ctx.BillyCuratorData.publishBlurblet('😀|😎');
assert.strictEqual(published.recordType,'published-curator-record');
assert.strictEqual(published.blurblet,'Test');
assert.strictEqual(Object.prototype.hasOwnProperty.call(published,'notes'),false);
load('engine/game/collections/collection-service.js');
const c=ctx.BillyCollectionService.blank('Test','🧪');c.draft.members=['😀|😀','😀|😀'];
const projection=ctx.BillyCollectionService.publicProjection(c);
assert.strictEqual(projection.schemaVersion,1);assert.deepStrictEqual(Array.from(projection.members),['😀|😀']);
console.log('Data contract tests passed.');
