const fs=require('fs'),vm=require('vm'),assert=require('assert');
const fieldsCode=fs.readFileSync('engine/systems/analysis/analysis-fields.js','utf8');
const jobsCode=fs.readFileSync('engine/systems/analysis/analysis-jobs.js','utf8');
const store=new Map();const context={window:{},localStorage:{setItem:(k,v)=>store.set(k,v),getItem:k=>store.get(k)},setTimeout,console};vm.createContext(context);vm.runInContext(fieldsCode,context);vm.runInContext(jobsCode,context);
const fields=context.window.BillyAnalysisFields,api=context.window.BillyAnalysisJobs;
assert(fields,'analysis field registry should exist');
assert.equal(fields.get('field_color_dominant_general').displayName,'Dominant Color');
assert.equal(fields.get('field_color_dominant_brightness').displayName,'Dominant Color Brightness');
assert.deepEqual(fields.optionSets().options_color_brightness_v1.options.map(x=>x.id),['color_brightness_light','color_brightness_medium','color_brightness_dark','color_brightness_mixed']);
assert(fields.option('color_pink'),'general colors must have permanent option IDs');
assert(api,'analysis API should exist');
const row=['🐷','🐷','pig_face','20240101','https://example.test/pig.png'];
const report=api.normalizeReport({report:{provider:{displayName:'Test Vision'},detectedCharacteristics:[{kind:'field',fieldId:'field_primary_subject',label:'Pig',confidence:.98,reason:'Visible pig form.',candidates:[{label:'Pig',value:'Pig',optionId:null,confidence:.98,reason:'Visible pig form.'},{label:'Animal',value:'Animal',optionId:null,confidence:.65,reason:'Broader visible class.'}]}],visualAnalysis:'A pink pig-like figure.',additionalObservations:[],issues:[],contradictions:[],remainingCategories:[]}},row);
assert(report.id.startsWith('analysis_report_'),'report must have a permanent ID');
assert(report.mashupId,'report must reference a canonical mashup ID');
assert.equal(report.detectedCharacteristics[0].candidates.length,2,'ranked alternatives must be preserved');
assert.equal(report.detectedCharacteristics[0].confidence,.98,'exact confidence must be preserved');
const job=api.create([row]);assert.equal(job.total,1);assert.equal(job.state,'queued');console.log('analysis jobs v3.1.2a: ok');
